mirToolboxFolder = 'mirtoolbox1.8.2';
outDir = fullfile(pwd, "pymirtoolbox");
appFile = which("feature_dispatcher.m");

buildResults = compiler.build.pythonPackage(appFile, ...
PackageName="pymirtoolbox", ...
OutputDir=outDir, ...
AdditionalFiles={mirToolboxFolder}, ...
Verbose="on");